services:
  uhok-backend:
    build: ../uhok-backend
    container_name: uhok-backend
    env_file:
      - ../uhok-backend/.env
    expose:
      - "9000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  # = 프론트엔드 (Nginx가 React 빌드 결과를 서빙 + /api 프록시)
  uhok-web:
    build: ../uhok-frontend        # 프론트 Dockerfile(멀티스테이지: 빌드→nginx)
    container_name: uhok-web
    ports:
      - "3001:80"                   # 외부는 3001로 접속
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro   # /api 프록시 설정
    depends_on:
      - uhok-backend
    restart: always
