services:
  uhok-backend:
    build:
      context: ../uhok-backend
      dockerfile: Dockerfile
    image: uhok-backend:0.1.0
    container_name: uhok-backend
    expose:
      - "9000"
    ports:
      - "9000:9000"
    env_file:
      - ../uhok-backend/.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - app_net
    restart: unless-stopped

  uhok-frontend:
    build:
      context: ../uhok-frontend
      dockerfile: Dockerfile
    image: uhok-frontend:0.1.0
    container_name: uhok-frontend
    expose:
      - "80"
    networks:
      - app_net
    restart: unless-stopped

  uhok-nginx:
    image: nginx:1.25-alpine
    container_name: uhok-nginx
    depends_on:
      - uhok-backend
      - uhok-frontend
    ports:
      - "3001:80"   # localhost:3001 로 접근
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_net
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
